services:
  schoolas-api:
    image: schoolas-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=school_as;Username=postgres;Password=password;Ssl Mode=Disable
      - JWT_SECRET=SecretKeyMustBeLongEnough1234567890
      - JWT_ISSUER=SchoolAsApi
      - JWT_AUDIENCE=SchoolAsClient
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:13000
    depends_on:
      - db
    networks:
      - schoolas-network

  schoolas-web:
    build:
      context: ../School_AS_Frontend
      dockerfile: Dockerfile
    ports:
      - "13000:80"
    environment:
      - VITE_API_URL=http://localhost:15000/api
    depends_on:
      - schoolas-api
    networks:
      - schoolas-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_as
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - schoolas-network

volumes:
  postgres-data:


networks:
  schoolas-network:
    driver: bridge
