services:
  schoolas-api:
    image: schoolas-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=school_as
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SSL_MODE=Disable
      - JWT_SECRET=Th1sIsASup3rS3cr3tKeyF0rSch00lAsProject!
      - JWT_ISSUER=SchoolAsApi
      - JWT_AUDIENCE=SchoolAsClients
    depends_on:
      - postgres-db
    networks:
      - schoolas-network

  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_as
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - schoolas-network

volumes:
  postgres-data:


networks:
  schoolas-network:
    driver: bridge
