services:
  - type: web
    name: schoolas-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: schoolas-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ISSUER
        value: SchoolAsApi
      - key: JWT_AUDIENCE
        value: SchoolAsUser

databases:
  - name: schoolas-db
    databaseName: school_as
    user: school_user
    plan: free
